baseURL: "https://unitedlambdas.github.io"
languageCode: "en-us"
title: "United Lambdas"
pygmentsstyle: 'monokai'
metaDataFormat: yaml

# Theme settings
# theme: novela
theme: "hugo-theme-novela"
paginate: 6
social:
  github: "http://github.com/unitedlambdas/"
taxonomies:
  author: authors
